// Generated by typings
// Source: https://raw.githubusercontent.com/types/typed-dateformat/80dfd72ec9a4383a279a6f419a660059502038e5/lib/dateformat.d.ts
declare module 'dateformat' {
interface IDateFormat {
  (date?: Date | string | number, mask?: string, utc?: boolean, gmt?: boolean): string;
  masks: { [name: string]: string; };
}

const dateformat: IDateFormat;

export = dateformat;
}
