// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-graceful-fs/84adcae7061f5f71409cac66fc6628929e536022/graceful-fs.d.ts
declare module 'graceful-fs' {
export * from 'fs';
}
